### ISSUE TITLE
Cluster with 3 master nodes doesn't allow any node to be missing

### ISSUE THREAD

**Issue by scibi** [debops/ansible-elasticsearch#22]
Right now `discovery.zen.minimum_master_nodes` is set to 3 if you have 3 master nodes. I'm wondering if it is correct. Official documentation is not precise because it says it should be equal to (total number of master-eligible nodes / 2 + 1). It doesn't say anything about rounding. IMHO we should use `floor` here so we would have `3/2 + 1 = 1 + 1 = 2`. Just like in this recommendation: https://www.loggly.com/blog/nine-tips-configuring-elasticsearch-for-high-performance/

We can replace `round` with `round(0, 'floor')` or just remove `+ 1` here:

https://github.com/debops/ansible-elasticsearch/blob/6e791e5b91ef0f4af1628fb36b608042b05c0a46/defaults/main.yml#L190-L191

**Comment by drybjed** [comment]
Originally I planned either for 1 node instance, or at least a 3 node instance to achieve quorum. I suppose that 2 + 1 cluster is valid as well, and in this case having hard minimum of 3 potential masters might be tricky.

I would go with the `floor` approach, +1 sounds best in clusters with higher number of nodes to ensure that a cluster with even number of hosts always has majority quorum.

Do you want to create a PR or should I do it?

**Comment by scibi** [comment]
I'll do it :)
