### ISSUE TITLE
gateway.type and elastic search 2.x

### ISSUE THREAD

**Issue by ledjon** [debops/ansible-elasticsearch#9]
The "gateway.type" setting seems to break elasticsearch 2.x (2.3, in my case)

Line in question:

https://github.com/debops/ansible-elasticsearch/blob/master/templates/etc/elasticsearch/elasticsearch.yml.j2#L248

The error log will throw:

```
java.lang.IllegalArgumentException: Unknown [gateway] type [local]
        at org.elasticsearch.common.util.ExtensionPoint$SelectedType.bindType(ExtensionPoint.java:146)
        at org.elasticsearch.gateway.GatewayModule.configure(GatewayModule.java:53)
        at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
....
```

I would recommend that the template be updated to allow for "if elasticsearch_version == 2.x, remove line" sort of logic.  I can do this and put in a PR if you'd like.

There might be 1 or 2 more 2.x related changes that would be good to address as well.

**Comment by drybjed** [comment]
Sure, might be good idea for a PR. Currently the Travis-Ci test was failing, so i'm re-running it to see if anything needs fixing.
